# Generated by Django 4.2.17 on 2025-04-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag_Number', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(max_length=100)),
                ('weight', models.PositiveIntegerField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'bull'), ('female', 'heifer')], default='female', max_length=255)),
            ],
        ),
    ]
