# Generated by Django 4.2.17 on 2025-04-05 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='cow',
            name='tag_Number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Breed_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.breed')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cow')),
            ],
        ),
    ]
