# Generated by Django 4.2.17 on 2025-04-05 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_breed_alter_cow_tag_number_breed_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milking_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_created=True)),
                ('liters', models.FloatField()),
                ('session', models.CharField(choices=[('morning', 'morning'), ('noon', 'noon'), ('evening', 'evening')], default='noon', max_length=255)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cow')),
            ],
        ),
    ]
