# Generated by Django 4.2.17 on 2025-04-05 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_milking_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milking_record',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Feeding_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(max_length=255)),
                ('feed_quantity', models.FloatField()),
                ('day', models.DateField(auto_now_add=True)),
                ('session', models.CharField(choices=[('morning', 'morning'), ('noon', 'noon'), ('evening', 'evening')], default='noon', max_length=255)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cow')),
            ],
        ),
    ]
