# Generated by Django 4.2.17 on 2025-04-05 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_milking_record_day_feeding_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(max_length=255)),
                ('feed_quantity', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='feeding_record',
            name='feed_quantity',
        ),
        migrations.AddField(
            model_name='feeding_record',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feeding_record',
            name='feed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.feed'),
        ),
    ]
