# Generated by Django 4.2.17 on 2025-04-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_feed_remove_feeding_record_feed_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cow',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
    ]
