# Generated by Django 4.2.17 on 2025-04-05 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_cow_age_alter_cow_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milk_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litres', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('cost', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='feeding_record',
            old_name='day',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='milking_record',
            old_name='day',
            new_name='date',
        ),
        migrations.CreateModel(
            name='Feed_Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('cost', models.FloatField(default=0)),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.feed')),
            ],
        ),
    ]
