# Generated by Django 4.2.17 on 2025-04-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_milk_sales_rename_day_feeding_record_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinary_Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('medicine', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('cost', models.FloatField(default=0)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Immunisation_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('medicine', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('next_date', models.DateField(blank=True, null=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cow')),
            ],
        ),
    ]
