# Generated by Django 4.2.17 on 2025-04-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_veterinary_care_immunisation_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spraying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('next_date', models.DateField(blank=True, null=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Birth_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('calf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cow')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='base.cow')),
            ],
        ),
    ]
