# Generated by Django 5.2 on 2025-04-08 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_litres_manure_sales_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding_record',
            name='session',
            field=models.CharField(choices=[('morning', 'morning'), ('noon', 'noon'), ('evening', 'evening')], default='morning', max_length=255),
        ),
        migrations.AlterField(
            model_name='milk_sales',
            name='litres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.milking_record'),
        ),
        migrations.AlterField(
            model_name='milking_record',
            name='session',
            field=models.CharField(choices=[('morning', 'morning'), ('noon', 'noon'), ('evening', 'evening')], default='morning', max_length=255),
        ),
        migrations.DeleteModel(
            name='Spraying',
        ),
    ]
