# Generated by Django 5.2 on 2025-04-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_milk_sales_litres'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veterinary_cost', models.FloatField(default=0)),
                ('month', models.DateField()),
            ],
        ),
    ]
