# Generated by Django 5.2 on 2025-04-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_monthlyreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veterinary_care',
            old_name='cost',
            new_name='veterinary_cost',
        ),
    ]
